### ISSUE TITLE
Unable to labelling bounding boxes

### ISSUE THREAD

**Issue by suravijayjilla** [Etienne-Meunier/LabelTool#1]
Hi,

It was awesome. But I have doubt, how to write/give a label to the selected bounding box in a video.
Please guide me on this.

**Comment by Etienne-Meunier** [comment]
Hi ! Thank you very much. For now, it will output a CSV with the position of the bounding boxes without a label because we can only label one object by video but I am working to add this functionality

**Comment by suravijayjilla** [comment]
Hi, Thanks for your reply. Once you completed the work please share me the code.
Or share your work progress I will try my best to add this functionality.
